#!/bin/bash
# Showing the usage of disk space
#
# Thomas R. N. Jansson
# 27 october 2009 
# Version 1.1
#
# Parameters:
#       config   (required)
#       autoconf (optional - used by munin-config)

#RAWDIR="/`basename $0 | sed 's/^df_//g'`"
DIR="/home"

# Tests wether or not DIR exists
if [ "$1" = "autoconfig" ]; then
    if [ -d $DIR ]; then
        echo 'yes'
        exit 0
    else
        echo '$DIR does not exist on this machine'
        exit 1
    fi
fi

# CONF
if [ "$1" = "config" ]; then

        echo "graph_title Storage usage on $DIR"
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel GB'
        echo 'graph_category disk'

        echo "used.info The total disk space in GBytes that is in use on $DIR."
        echo "used.type GAUGE"
        echo "used.draw AREA"
        echo "used.label Used";
        #echo "used.cdef used,1024,*"
        echo "used.min 0"
        
        echo "avail.info The total capacity in GBytes for the $DIR."
        echo "avail.type GAUGE"
        echo "avail.draw STACK"
        echo "avail.label Available"
        #echo "avail.cdef avail,1024,*"
        echo "avail.min 0";
        
        echo "avail.warning 100.0:" 
        echo "avail.critical 25.0:" 
        #100GB = 104857600KB
        #50GB  = 52428800KB
        
        echo "total.info The total capacity in GBytes for the $DIR."
        echo "total.type GAUGE"
        echo "total.draw LINE2"
        echo "total.label Total"
        #echo "total.cdef total,1024,*"
        echo "total.min 0"

        exit 0
fi

if [ -d $DIR ]; then
    echo total.value `df -P $DIR | grep $DIR$ | awk '{print $2/1048576}'` 
    echo used.value  `df -P $DIR | grep $DIR$ | awk '{print $3/1048576}'` 
    echo avail.value `df -P $DIR | grep $DIR$ | awk '{print $4/1048576}'` 
fi
